### PR TITLE
Cache some scummvm artifacts

### PR DESCRIPTION
**Pull request by neuromancer**
This is another attempt to have a working cache in this github action

### CODE REVIEW

**Comment by neuromancer** [comment]
@chkuendig can you please re-run the CI tests here? (or close this PR if you don't like it). It will be nice to know if this caching works as expected or not.

**Comment by chkuendig** [comment]
Done, lets see if it works. Did it work in your repo?

**Comment by neuromancer** [comment]
It was working in my fork (which is now broken with the javascript error, for some reason, I need resync it with upstream, e.g. this repository)

**Comment by neuromancer** [comment]
The build is almost complete. When it finishes, please re-run the action so we can see how much time it takes using the cache.

**Comment by neuromancer** [comment]
It seems it failed because the deployment was not possible (as expected):

```
remote: Permission to chkuendig/scummvm-demo.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/chkuendig/scummvm-demo.git/': The requested URL returned error: 403
```

I'm afraid this will be a blocker to test if the cache works or not, before merging :disappointed:

**Comment by neuromancer** [comment]
Happy to this this was merged!. Can you try re-running the action to see if the cache decreases the build time?

**Pull request merged**
